### ISSUE TITLE
action-rubocop stopped working because it is apparently using wrong version of ruby

### ISSUE THREAD

**Issue by leticiarodrigues5** [reviewdog/action-rubocop#119]
So, this happened suddenly, was working until last friday.
```
Run reviewdog/action-rubocop@v2.5.0
Run $GITHUB_ACTION_PATH/script.sh
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
 Installing rubocop with extensions ... https://github.com/rubocop/rubocop
  Successfully installed unicode-display_width-1.8.0
  Successfully installed ruby-progressbar-1.13.0
  Successfully installed ast-2.4.2
  Successfully installed parser-3.3.4.2
  Successfully installed rubocop-ast-1.32.0
  Successfully installed regexp_parser-2.9.2
  Successfully installed rainbow-3.1.1
  Successfully installed parallel-1.26.2
  Successfully installed rubocop-1.7.0
  9 gems installed
  ERROR:  Error installing rubocop-rails:
  	The last version of activesupport (>= 4.2.0) to support your Ruby & RubyGems was 7.1.3.4. Try installing it with `gem install activesupport -v 7.1.3.4` and then running the current command again
  	activesupport requires Ruby version >= 3.1.0. The current ruby version is 2.7.1.83.
  Successfully installed rack-3.1.7
  Successfully installed securerandom-0.3.1
  Successfully installed drb-2.2.1
  Successfully installed base64-0.2.0
  Successfully installed connection_pool-2.4.1
  Successfully installed concurrent-ruby-1.3.4
  Successfully installed tzinfo-2.0.6
  Successfully installed i18n-1.[14](https://github.com/isohub-br/photo-webapp/actions/runs/10358426537/job/28672604393?pr=1989#step:4:15).5
  Error: Process completed with exit code 1.
```

This is my workflow:
```
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.7.1
        uses: ruby/setup-ruby@v1.152.0
        with:
          ruby-version: 2.7.1
      - name: run rubocop
        uses: reviewdog/action-rubocop@v2.5.0
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review
```
