### ISSUE TITLE
Flaky linting: obsolete configuration error

### ISSUE THREAD

**Issue by bmulholland** [reviewdog/action-rubocop#135]
My lints are failing intermittently, with these errors:
```
   Error: `Rails` cops have been extracted to the `rubocop-rails` gem.
  (obsolete configuration found in .rubocop.yml, please update it)
```

There shouldn't be anything intermittent about this, because we use the rubocop version from our Gemfile:
```
      - name: Check code formatting - rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          # Since we include all the rubocop gems in our Gemfile, they are
          # installed already. By using bundler, we don't need this action to
          # install a bunch of gems
          use_bundler: true
          # So don't need to install rubocop or its extensions
          skip_install: true
          # Project has zero rubocop issues, so we can fail if there are any, anywhere
          fail_level: any
          filter_mode: nofilter
```

We can never reproduce this issue locally. I've compared the GHA output from a failing run vs a successful one (a re-run on the same PR, which doesn't change anything related). There's no differences in anything, including version of reviewdog used.

I'm happy to do most of the investigation myself, but need some help: How do we even begin to investigate what the issue could be?
* Is the issue with an incorrect version of Rubocop being used? How would we know?
* Does rubocop itself have some form of flake? How could we narrow that down?
* Do you see an issue in our configuration above?
