### ISSUE TITLE
Shows my Profile pic (pointing to my profile) instead of GitHub action icon

### ISSUE THREAD

**Issue by kapso** [reviewdog/action-rubocop#14]
First, thanks a lot for creating this, so useful 🎉 

In my review comments, I am seeing my profile and not the GitHub action profile? Is there a way to fix this?

`secrets.GIT_HUB_TOKEN` this is the token that I created based on these instructions - https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

Could this be a token issue?

----
<img width="567" alt="Screen Shot 2020-07-01 at 1 14 01 PM" src="https://user-images.githubusercontent.com/344198/86287274-c1dd0080-bb9c-11ea-9157-1db774a0fec3.png">
-----

Config that I am using...

```yml
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{secrets.GIT_HUB_TOKEN}}
          reporter: github-pr-review # Default is github-pr-check
```
