### ISSUE TITLE
Latest version no longer installs custom rubocop extensions where the name does not begin with rubocop-

### ISSUE THREAD

**Issue by dnorth98** [reviewdog/action-rubocop#17]
We've been using this action for sometime with a custom rubocop extension (which passes in a config loaded from a gemfile). The workflow looks like:

```
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: 0.88
          rubocop_extensions: rubocop-performance:1.5.1 rubocop-minitest rewind-ruby-style
          github_token: ${{ secrets.github_token }}
          filter_mode: file
```

The extension is `rewind-ruby-style`.

This was working fine but it looks like the commit on Sept 3 (https://github.com/reviewdog/action-rubocop/commit/e6c18331c19648a2f9e1e7aecfb2c20f688668d7#diff-b958f585a04af5ee2087610ea7180f34) assumes all extensions will begin with the string `rubocop`.  Which isn't correct when using an extension as a custom rubocop "load from gem" config.

Could this be changed back to allow extensions that don't have the string rubocop in them?
