### ISSUE TITLE
Versions past 1.7.1 fail to install the rubocop gem

### ISSUE THREAD

**Issue by dnorth98** [reviewdog/action-rubocop#34]
It looks like since 1.7.1, the action has been broken.  I'm guessing not many people may have noticed because this just caues the check to succeed :awk:

![image](https://user-images.githubusercontent.com/6616703/109696041-9dd22480-7b5a-11eb-8676-a145242c87ae.png)

I took a look at the diff and I can't quite see why it would now be broken but certainly any version past 1.7.1 exhibits this error.

**Comment by mgrachev** [comment]
Hey @dnorth98 👋

Do you use the setup-ruby action in your workflow file?

Example:
```yaml
name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          github_token: ${{ secrets.github_token }}
```
