### ISSUE TITLE
Add ability to skip install of rubocop and extensions

### ISSUE THREAD

**Issue by szechyjs** [reviewdog/action-rubocop#42]
If a previous step in our action like `setup-ruby` already installs rubocop and the required extensions based on `Gemfile` there should be no need to do it again here. It would be nice to be able to skip the rubocop install and just run it.

```yml
- name: Setup Ruby
   uses: ruby/setup-ruby@v1
     with:
       bundler-cache: true
```
