### ISSUE TITLE
How i can use my own robocop rule?

### ISSUE THREAD

**Issue by emersonassis** [reviewdog/action-rubocop#44]
How do I set up to use my own robocop rules?

Does this action already use the rule configured in the project?

**Comment by mgrachev** [comment]
@emersonassis Hi 👋

This action simply runs rubocop on your codebase, so you can pass rubocop your config file like this:
```yaml
- name: rubocop
  uses: reviewdog/action-rubocop@v1
  with:
    rubocop_flags: --config your_rubocop_config.yaml
```
