### ISSUE TITLE
Undefined method `begin' for PseudoSourceRange

### ISSUE THREAD

**Issue by nononoy** [reviewdog/action-rubocop#55]
I'm getting an error during execution. Can provide more details if needed
```
undefined method `begin' for #<RuboCop::Cop::Offense::PseudoSourceRange:0x000055906792fa48>
Did you mean?  begin_pos
/home/runner/work/_actions/reviewdog/action-rubocop/v2/rdjson_formatter/rdjson_formatter.rb:41:in `build_diagnostic'
```
Workflow config:
```
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: 0.90.0
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review
          fail_on_error: true
```
