### ISSUE TITLE
gem install was failed with Ruby 2.6.6

### ISSUE THREAD

**Issue by SugiKent** [reviewdog/action-rubocop#61]
Hi, thank you for such useful library.

I want to specify rails version of rubocop-rails by passing to `RAILS_VERSION` environment variable to rubocop-rails.

I got below errors during action-rubocop. As you see, the errors were caused by dependencies resolving errors. I think rubocop-rails tries to install the latest version of rails, even if developers provide desired version of rubocop-rails like this `rubocop_extensions: rubocop-rails:gemfile`. However the rails(activesupport) 6.1.4.4 does not support ruby 2.6.6, so the errors occurred.

```
Run reviewdog/action-rubocop@v1
Run $GITHUB_ACTION_PATH/script.sh
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
 Installing rubocop with extensions ... https://github.com/rubocop/rubocop
  Successfully installed parallel-1.21.0
  Successfully installed ast-2.4.2
  Successfully installed parser-3.0.3.2
  Successfully installed rainbow-3.0.0
  Successfully installed regexp_parser-2.2.0
  Successfully installed rubocop-ast-1.15.0
  Successfully installed ruby-progressbar-1.11.0
  Successfully installed unicode-display_width-2.1.0
  Successfully installed rubocop-1.23.0
  9 gems installed
  ERROR:  Error installing rubocop-rails:
  	The last version of activesupport (>= 4.2.0) to support your Ruby & RubyGems was 6.1.4.4. Try installing it with `gem install activesupport -v 6.1.4.4` and then running the current command again
  Successfully installed concurrent-ruby-1.1.9
  Successfully installed i18n-1.8.11
  Successfully installed tzinfo-2.0.4
  	activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.6.6.146.
  Error: Process completed with exit code 1.
``` 

Although we can provide desired rails version to rubocop-rails with some options (ex: RAILS_VERSION environment variable ), I couldn't pass RAILS_VERION by writing it in CI yaml file for reviewdog.

like this
```
name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    env:
      RAILS_VERSION: 6.1.4.1 # desired Rails version for rubocop-rails
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile rubocop-i18n:gemfile rubocop-rake:gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: added
```

Do you have any ideas to resolve the issue?
