### ISSUE TITLE
Takes too long

### ISSUE THREAD

**Issue by paulomcnally** [reviewdog/action-rubocop#64]
Is it normal that it takes so long if I just add the yml to the workflow?

```yaml
name: Review Dog
on:
  pull_request:
    branches: [develop]
jobs:
  rubocop:
    name: dog-pro
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7
      - run: gem install activesupport --version 6.1.4.3
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: $${{ secrets.github_token }}
          rubocop_version: 0.81.0
          rubocop_extensions: rubocop-rails:2.5.2
          reporter: github-pr-review
          fail_on_error: true
          tool_name: dog-pro

```

![Screen Shot 2022-01-07 at 15 37 57](https://user-images.githubusercontent.com/181533/148610712-3b59829b-9960-4616-9d73-b5c91e03b36b.png)

![Screen Shot 2022-01-07 at 15 38 20](https://user-images.githubusercontent.com/181533/148610747-03dc62c2-6463-4257-8093-e6b3efde583f.png)

I canceled it to prevent consuming too much time, I was not sure if it had been in an infinite loop.

**Comment by mgrachev** [comment]
Hi! Could you provide a log to check the problem?

**Comment by karlentwistle** [comment]
@paulomcnally we managed to work around this issue by only having RuboCop lint files that had changed

```ruby
name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Retrive and store changed ruby files
        run: echo "INPUT_RUBOCOP_FLAGS=$(git diff --name-only --diff-filter=ACMRTUXB origin/master | grep  -E "(\.rb$)" | tr '\n' ' ')" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        if: ${{ env.INPUT_RUBOCOP_FLAGS }}

      - name: Linting following files
        run: echo $INPUT_RUBOCOP_FLAGS
        if: ${{ env.INPUT_RUBOCOP_FLAGS }}

      - name: rubocop
        uses: BiggerPockets/action-rubocop@0b9fdc012b541882a0d8b74cc74ebbbab200bb30
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
        if: ${{ env.INPUT_RUBOCOP_FLAGS }}
```

The only complication was needing to fork this repo so we could stop `INPUT_RUBOCOP_FLAGS` from being overwritten https://github.com/BiggerPockets/action-rubocop/commit/0b9fdc012b541882a0d8b74cc74ebbbab200bb30

Thought I'd share incase its helpful to anyone else

**Comment by dbackeus** [comment]
> We managed to work around this issue by only having RuboCop lint files that have changed in the current pull request

Seems like this should be the default behaviour, or at least a simple option to enable?

Getting a linting failure because of code not touched in a given PR is not how we would like the action to behave.

**Comment by igray** [comment]
If it helps anyone else, this is very similar to the above, but does not require a fork:

```
name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.6

      - name: Fetch mainline branch for comparison (required for next step)
        run: git fetch origin main

      - name: Retrieve and store changed ruby files
        id: changed-files
        run: echo "CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB FETCH_HEAD | grep -E "(\.rb$)" | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Linting the following files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.CHANGED_FILES }}
        run: echo $CHANGED_FILES

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_flags: ${{ steps.changed-files.outputs.CHANGED_FILES }}
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          reporter: github-pr-review
```
