### ISSUE TITLE
getting REVIEWDOG_GITHUB_API_TOKEN error

### ISSUE THREAD

**Issue by rebebop** [reviewdog/action-rubocop#66]
Hi,
I am trying to use this action but every time I run it it's giving me this error, the rubocop itself doesn't have any errors.

```
reviewdog: environment variable $REVIEWDOG_GITHUB_API_TOKEN is not set
```
This fails the action. 
I have also tried to manually set the `github_token` param (as it's optional), but still the same.

Here is my workflow file
```
name: "🏗 Lint"

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup ruby and install dependencies
        uses: ruby/setup-ruby@v1.92.0
        with:
          bundler-cache: true
      - name: Setup rubocop with reviewdog
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ github.token }}
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-minitest:gemfile rubocop-performance:gemfile rubocop-thread_safety:gemfile

```
