### ISSUE TITLE
[BUG] Invalid request. Only 65535 characters are allowed; 70292 were supplied.

### ISSUE THREAD

**Issue by Speak2Erase** [reviewdog/action-rubocop#67]
Any action run I try fails with `Invalid request. Only 65535 characters are allowed; 70292 were supplied.`
Configuration:
```yml
name: Rubocop
on: pull_request
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-check # Default is github-pr-check
```
