### ISSUE TITLE
Cache ruby gems to speed up installation

### ISSUE THREAD

**Issue by kleinjm** [reviewdog/action-rubocop#83]
It takes about a minute to install the gems with extensions on my CI runs.

Would it be possible to cache the gem installation?
Another thought - I use the `ruby/setup-ruby@v1` to set up ruby before running review dog. Would it be possible to use the same cache as that GH action?

**Comment by nyancat3** [comment]
@kleinjm How about using `skip_install` and `use_bundler` options with `bundler-cache: true` of [setup-ruby](https://github.com/ruby/setup-ruby)?

```
name: reviewdog
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review # Default is github-pr-check
          skip_install: true
          use_bundler: true
```
